server:
  port: 8000

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/home"
    username: root
    password: rhksghsadf